CREATE SCHEMA IF NOT EXISTS "users";

CREATE TABLE IF NOT EXISTS "users"."User" (
  "idUser" CHAR(12) NOT NULL,
  "idTelegram" INT NOT NULL,
  "email" VARCHAR(255) NULL,
  "password" VARCHAR(255) NULL,
  "linkCode" VARCHAR(255) NULL,
  PRIMARY KEY ("idUser"),
  CONSTRAINT "idTelegram_UNIQUE" UNIQUE ("idTelegram")
);


CREATE TABLE IF NOT EXISTS "users"."Doctor" (
  "idDoctor" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "User_idUser" CHAR(12) NOT NULL,
  PRIMARY KEY ("idDoctor"),
  CONSTRAINT "fk_Doctor_User"
    FOREIGN KEY ("User_idUser")
    REFERENCES "users"."User" ("idUser")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE INDEX IF NOT EXISTS "fk_Doctor_User_idx" ON "users"."Doctor" ("User_idUser" ASC);

CREATE TABLE IF NOT EXISTS "users"."Alert" (
  "idAlert" serial PRIMARY KEY,
  "firstAlertGiven" BOOLEAN NULL,
  "secondAlertGiven" BOOLEAN NULL,
  "thirdAlertGiven" BOOLEAN NULL,
  "medicationAlertDate" TIMESTAMP NULL,
  "User_idUser" CHAR(12) NOT NULL,
  CONSTRAINT "idAlert_UNIQUE" UNIQUE ("idAlert"),
  CONSTRAINT "fk_Alert_User1"
    FOREIGN KEY ("User_idUser")
    REFERENCES "users"."User" ("idUser")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE INDEX IF NOT EXISTS "fk_Alert_User1_idx" ON "users"."Alert" ("User_idUser" ASC);

CREATE TABLE IF NOT EXISTS "users"."Admin" (
  "idAdmin" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "User_idUser" CHAR(12) NOT NULL,
  PRIMARY KEY ("idAdmin"),
  CONSTRAINT "fk_Admin_User1"
    FOREIGN KEY ("User_idUser")
    REFERENCES "users"."User" ("idUser")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE INDEX IF NOT EXISTS "fk_Admin_User1_idx" ON "users"."Admin" ("User_idUser" ASC);

CREATE TABLE IF NOT EXISTS "users"."Consent" (
  "idconsent" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "message" TEXT NOT NULL,
  "date" TIMESTAMP NOT NULL,
  "User_idUser" CHAR(12) NOT NULL,
  PRIMARY KEY ("idconsent"),
  CONSTRAINT "fk_consent_User1"
    FOREIGN KEY ("User_idUser")
    REFERENCES "users"."User" ("idUser")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE INDEX IF NOT EXISTS "fk_consent_User1_idx" ON "users"."Consent" ("User_idUser" ASC);

CREATE TABLE IF NOT EXISTS "users"."Measurement" (
  "idMeasurement" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "systolic" INT NOT NULL,
  "diastolic" INT NOT NULL,
  "heartRate" INT NULL,
  "datetime" TIMESTAMP NOT NULL,
  "User_idUser" CHAR(12) NOT NULL,
  PRIMARY KEY ("idMeasurement"),
  CONSTRAINT "fk_Measurement_User1"
    FOREIGN KEY ("User_idUser")
    REFERENCES "users"."User" ("idUser")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE INDEX IF NOT EXISTS "fk_Measurement_User1_idx" ON "users"."Measurement" ("User_idUser" ASC);


CREATE TABLE IF NOT EXISTS "users"."UserLabel" (
  "idUserLabel" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "label" VARCHAR(255) NOT NULL,
  "User_idUser_User" CHAR(12) NOT NULL,
  "User_idUser_Doctor" CHAR(12) NOT NULL,
  PRIMARY KEY ("idUserLabel"),
  CONSTRAINT "fk_UserLabel_User1"
    FOREIGN KEY ("User_idUser_User")
    REFERENCES "users"."User" ("idUser")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_UserLabel_User2"
    FOREIGN KEY ("User_idUser_Doctor")
    REFERENCES "users"."User" ("idUser")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX IF NOT EXISTS "labelIndex" ON "users"."UserLabel" ("User_idUser_User", "User_idUser_Doctor");
CREATE INDEX IF NOT EXISTS "fk_UserLabel_User1_idx" ON "users"."UserLabel" ("User_idUser_User" ASC);
CREATE INDEX IF NOT EXISTS "fk_UserLabel_User2_idx" ON "users"."UserLabel" ("User_idUser_Doctor" ASC);

CREATE TABLE IF NOT EXISTS "users"."UserStat" (
  "idUserStat" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "telegramInsertions" INT NOT NULL DEFAULT 0,
  "websiteInsertions" INT NOT NULL DEFAULT 0,
  "User_idUser" CHAR(12) NOT NULL,
  PRIMARY KEY ("idUserStat"),
  CONSTRAINT "fk_UserStat_User1"
    FOREIGN KEY ("User_idUser")
    REFERENCES "users"."User" ("idUser")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX IF NOT EXISTS "fk_UserStat_User1_idx" ON "users"."UserStat" ("User_idUser" ASC);